# Generated by Django 4.2.29 on 2026-03-07 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie_database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_data', models.JSONField()),
                ('start_time_offset', models.FloatField(help_text='Start time in seconds within the movie')),
                ('duration', models.FloatField(help_text='Duration of this fingerprint segment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='movie_database.movie')),
            ],
        ),
    ]
