# Generated by Django 4.2.29 on 2026-03-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('composer', models.CharField(max_length=255)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('genre', models.CharField(max_length=100)),
                ('poster_url', models.URLField(blank=True, max_length=500, null=True)),
                ('trailer_url', models.URLField(blank=True, max_length=500, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
