# Generated by Django 4.2.29 on 2026-03-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cloud_bucket',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='cloud_file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
